# Generated by Django 4.2.4 on 2023-12-07 02:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Pheflux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
