# Generated by Django 4.2.4 on 2023-08-23 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pheflux', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='compania',
            new_name='company',
        ),
    ]
