# Generated by Django 4.2.4 on 2023-08-23 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pheflux', '0002_rename_compania_userprofile_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='nombre',
            new_name='name',
        ),
    ]
