# Generated by Django 4.2.4 on 2023-12-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pheflux', '0002_update_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Pheflux/media')),
            ],
        ),
    ]
